name: ci
on:
  push:
    branches:
      - '*'

env:
  GO_VERSION: 1.17

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
